[build]
  environment = { RUBY_VERSION = "3.0.1" }
  command = "ruby app.rb"

[[redirects]]
  from = "/404"
  to = "/index.erb"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.erb"
  status = 200